/*
 * This file is generated by jOOQ.
 */
package kata.jooq;


import kata.jooq.tables.FlywaySchemaHistory;
import kata.jooq.tables.Item;
import kata.jooq.tables.records.FlywaySchemaHistoryRecord;
import kata.jooq.tables.records.ItemRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY__PK_FLYWAY_SCHEMA_HISTORY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("pk_flyway_schema_history"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<ItemRecord> ITEM__PK_ITEM = Internal.createUniqueKey(Item.ITEM, DSL.name("pk_Item"), new TableField[] { Item.ITEM.ID }, true);
}
