/*
 * This file is generated by jOOQ.
 */
package kata.jooq;


import kata.jooq.tables.Items;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>Items</code>.
     */
    public static final Items ITEMS = Items.ITEMS;
}
