/*
 * This file is generated by jOOQ.
 */
package kata.jooq;


import kata.jooq.tables.FlywaySchemaHistory;
import kata.jooq.tables.Item;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>Item</code>.
     */
    public static final Item ITEM = Item.ITEM;
}
