/*
 * This file is generated by jOOQ.
 */
package kata.jooq.tables.records;


import kata.jooq.tables.Item;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Item.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Item.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Item.SKU</code>.
     */
    public void setSku(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Item.SKU</code>.
     */
    public String getSku() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Item.PRICE</code>.
     */
    public void setPrice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Item.PRICE</code>.
     */
    public Integer getPrice() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemRecord
     */
    public ItemRecord() {
        super(Item.ITEM);
    }

    /**
     * Create a detached, initialised ItemRecord
     */
    public ItemRecord(Integer id, String sku, Integer price) {
        super(Item.ITEM);

        setId(id);
        setSku(sku);
        setPrice(price);
        resetChangedOnNotNull();
    }
}
