/*
 * This file is generated by jOOQ.
 */
package kata.jooq.tables.records;


import kata.jooq.tables.Item;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemRecord extends TableRecordImpl<ItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Item.SKU</code>.
     */
    public void setSku(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>Item.SKU</code>.
     */
    public String getSku() {
        return (String) get(0);
    }

    /**
     * Setter for <code>Item.PRICE</code>.
     */
    public void setPrice(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Item.PRICE</code>.
     */
    public Integer getPrice() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemRecord
     */
    public ItemRecord() {
        super(Item.ITEM);
    }

    /**
     * Create a detached, initialised ItemRecord
     */
    public ItemRecord(String sku, Integer price) {
        super(Item.ITEM);

        setSku(sku);
        setPrice(price);
        resetChangedOnNotNull();
    }
}
