/*
 * This file is generated by jOOQ.
 */
package kata.jooq.tables.records;


import kata.jooq.tables.Items;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemsRecord extends TableRecordImpl<ItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Items.sku</code>.
     */
    public void setSku(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>Items.sku</code>.
     */
    public String getSku() {
        return (String) get(0);
    }

    /**
     * Setter for <code>Items.price</code>.
     */
    public void setPrice(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Items.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemsRecord
     */
    public ItemsRecord() {
        super(Items.ITEMS);
    }

    /**
     * Create a detached, initialised ItemsRecord
     */
    public ItemsRecord(String sku, Integer price) {
        super(Items.ITEMS);

        setSku(sku);
        setPrice(price);
        resetChangedOnNotNull();
    }
}
